import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

export interface LarkDocumentBinding { documentKey: string; nodeToken: string; documentId: string; lastRevisionId: number; sourceCommitSha?: string; sourceRevisions: Record<string, string>; sourceRevisionSetHash?: string; managedSectionHashes: Record<string, string>; managedBlockIds: Record<string, string[]>; verifiedAt: string; migrationState?: "legacy_repo_unknown" }
export interface ExplicitBindingInput { documentKey: string; nodeToken: string; documentId: string; revisionId: number; sourceRevisions: Record<string, string>; sourceRevisionSetHash: string; managedSectionHashes?: Record<string, string>; managedBlockIds?: Record<string, string[]>; verifiedAt: string }
export interface LarkBindingCandidate { nodeToken: string; documentId: string; title: string; parentNodeToken?: string; revisionId: number }

export class LarkDocumentBindingStore {
  constructor(private readonly filePath: string) { mkdirSync(dirname(filePath), { recursive: true }); }
  private read(): Record<string, LarkDocumentBinding> { if (!existsSync(this.filePath)) return {}; try { const value = JSON.parse(readFileSync(this.filePath, "utf8")) as Record<string, LarkDocumentBinding>; return Object.fromEntries(Object.entries(value).map(([key, binding]) => [key, { ...binding, ...(binding.sourceRevisions ? {} : { sourceRevisions: {}, migrationState: binding.sourceCommitSha ? "legacy_repo_unknown" as const : undefined }), managedSectionHashes: binding.managedSectionHashes ?? {}, managedBlockIds: binding.managedBlockIds ?? {} }])); } catch { return {}; } }
  private write(value: Record<string, LarkDocumentBinding>): void { const tmp = `${this.filePath}.${process.pid}.tmp`; writeFileSync(tmp, JSON.stringify(value, null, 2)); renameSync(tmp, this.filePath); }
  resolve(documentKey: string): LarkDocumentBinding | null { return this.read()[documentKey] ?? null; }
  listCandidates(nodes: LarkBindingCandidate[]): LarkBindingCandidate[] { return [...nodes]; }
  bind(input: ExplicitBindingInput): LarkDocumentBinding { if (!input.nodeToken) throw new Error("nodeToken is required"); if (!input.documentId) throw new Error("documentId is required"); if (!Number.isInteger(input.revisionId) || input.revisionId < 0) throw new Error("revisionId must be a non-negative integer"); const all = this.read(); const existing = all[input.documentKey]; if (existing && existing.nodeToken !== input.nodeToken) throw new Error(`document key already bound to ${existing.nodeToken}; unbind explicitly first`); for (const [key, binding] of Object.entries(all)) if (key !== input.documentKey && binding.nodeToken === input.nodeToken) throw new Error(`node token already bound to ${key}`); const binding: LarkDocumentBinding = { documentKey: input.documentKey, nodeToken: input.nodeToken, documentId: input.documentId, lastRevisionId: input.revisionId, sourceRevisions: input.sourceRevisions, sourceRevisionSetHash: input.sourceRevisionSetHash, managedSectionHashes: input.managedSectionHashes ?? {}, managedBlockIds: input.managedBlockIds ?? {}, verifiedAt: input.verifiedAt }; all[input.documentKey] = binding; this.write(all); return binding; }
  updateVerified(binding: LarkDocumentBinding): void { const all = this.read(); if (!all[binding.documentKey] || all[binding.documentKey].nodeToken !== binding.nodeToken) throw new Error("binding identity mismatch"); all[binding.documentKey] = binding; this.write(all); }
  remove(documentKey: string, expectedNodeToken: string): void { const all = this.read(); if (all[documentKey] && all[documentKey].nodeToken !== expectedNodeToken) throw new Error("binding token mismatch"); delete all[documentKey]; this.write(all); }
}
