//! Live integration test for Stage 0, task 6: proves the local-secure
//! profile's TLS port (6651) actually terminates TLS with our self-signed
//! CA, rather than silently staying plaintext the way `authenticationEnabled`
//! silently stayed off before task 3 (see task-6-brief.md's BINDING RULING
//! R37). Handshake-only: never builds a producer, consumer or subscription
//! (Stage 0 stays read-only; §1.3/B-01/B-03).
//!
//! Requires the local-secure profile:
//!   docker compose -f infra/broker/docker-compose.secure.yml up -d
//! and its certs, generated by:
//!   infra/broker/secure/generate-tls-certs.sh
//!
//! All tests here are `#[ignore]`d: `broker-pulsar-secure` must be started
//! only while this file is being run, then stopped immediately afterwards
//! (running it alongside the `pulsar` container that holds the user's real
//! business topics has already OOM-killed that container once on this VM).
//! Run explicitly with:
//!   cargo test --test broker_secure_tls -- --ignored
//!
//! This file only exercises the `pulsar` crate directly against the rig; it
//! does not touch `broker::adapters::pulsar::binary` — teaching the shipped
//! client to speak `pulsar+ssl://` with a token is Stage A's job, not this
//! infrastructure task's (see task-6-brief.md's scope boundary).

use pulsar::{Authentication, Pulsar, TokioExecutor};
use std::time::Duration;

// Deliberately the IP literal, not "localhost": on this machine "localhost"
// resolves to both 127.0.0.1 and ::1, and Docker Desktop's proxy accepts
// then immediately refuses the ::1 leg (nothing is actually listening on
// v6). The `pulsar` crate (6.9.0) shuffles resolved addresses and, when one
// address in the set fails with a *retryable* error (`ConnectionRefused`)
// and another fails with a *fatal* one (a real TLS/cert error), its
// `Connection::new` reports the retryable one and retries the whole set —
// burning through all `max_retries` (~40s) before surfacing a misleading
// "Connection refused" instead of the real, fast, correct TLS/auth error.
// That failure is real but says nothing about our TLS setup — another
// R37-shaped trap (a wrong-looking answer that isn't the one under test) —
// so pin to the IP literal to remove the ambiguous address entirely.
const TLS_URL: &str = "pulsar+ssl://127.0.0.1:6651";
const CORRECT_CA: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../infra/broker/secure/ca.cert.pem");
const WRONG_CA: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../infra/broker/secure/wrong-ca.cert.pem"
);
const ADMIN_JWT: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../infra/broker/secure/admin.jwt");

/// Generous but bounded: a hung TLS/auth handshake must show up as an
/// explicit error inside this window, not as this test timing out — a test
/// timeout looks identical to a broker that never enabled auth/TLS at all
/// and can't be told apart from a real "this connection would work" outcome.
const HANDSHAKE_BUDGET: Duration = Duration::from_secs(10);

fn admin_token() -> String {
    std::fs::read_to_string(ADMIN_JWT)
        .expect("admin.jwt must exist — run infra/broker/secure/generate-keys.sh")
        .trim()
        .to_string()
}

/// A bare-bones `log::Log` that prints ERROR/WARN records to stderr.
///
/// The `pulsar` crate's `Connection::new` collapses several distinct fatal
/// causes (TLS certificate mismatch, bad token, ...) into one generic
/// `io::Error::other("fatal error when connecting to the Pulsar server")`
/// once it decides no address is worth retrying — but on the way there it
/// logs the real, specific cause via `error!("connection error, not
/// retryable: {:?}", fatal_errors)`. Without a logger installed, that detail
/// is silently dropped and every failure looks identical from the outside.
/// Installing this is how the negative tests below can tell "wrong CA" and
/// "invalid token" apart, and how the report can quote the real cause
/// instead of the generic wrapper.
struct StderrLogger;

impl log::Log for StderrLogger {
    fn enabled(&self, metadata: &log::Metadata) -> bool {
        metadata.level() <= log::Level::Warn
    }

    fn log(&self, record: &log::Record) {
        if self.enabled(record.metadata()) {
            eprintln!("[pulsar-crate {}] {}", record.level(), record.args());
        }
    }

    fn flush(&self) {}
}

fn install_logger() {
    static ONCE: std::sync::Once = std::sync::Once::new();
    ONCE.call_once(|| {
        log::set_boxed_logger(Box::new(StderrLogger)).expect("install test logger");
        log::set_max_level(log::LevelFilter::Warn);
    });
}

/// Positive case: correct CA, valid JWT, `pulsar+ssl://` — this is the exact
/// shape of the user's QAT connection. Connect only; no producer, no
/// subscription.
#[tokio::test]
#[ignore = "requires broker-pulsar-secure up on 6651; see module docs"]
async fn tls_handshake_succeeds_with_correct_ca_and_valid_token() {
    install_logger();
    let build = Pulsar::builder(TLS_URL, TokioExecutor)
        .with_certificate_chain_file(CORRECT_CA)
        .expect("read correct CA file")
        .with_tls_hostname_verification_enabled(true)
        .with_auth(Authentication {
            name: "token".into(),
            data: admin_token().into_bytes(),
        })
        .build();

    match tokio::time::timeout(HANDSHAKE_BUDGET, build).await {
        Ok(Ok(_pulsar)) => {
            // Success: TLS handshake completed against our CA and the
            // broker accepted the admin token. Deliberately do nothing
            // else — Stage 0 never constructs a producer/consumer.
        }
        Ok(Err(e)) => panic!(
            "expected a successful TLS handshake with the correct CA and a valid \
             token, got an error instead: {e:?}"
        ),
        Err(_) => panic!(
            "connect timed out after {HANDSHAKE_BUDGET:?} instead of succeeding or \
             failing — this proves nothing about whether TLS/auth are on"
        ),
    }
}

/// Negative case #1: the broker's real cert is signed by our real CA, not by
/// this unrelated CA. If TLS were actually off (or the client silently fell
/// back to plaintext), this would connect fine — so a hard failure here is
/// exactly what distinguishes "TLS is on" from "something merely answered"
/// (BINDING RULING R37).
#[tokio::test]
#[ignore = "requires broker-pulsar-secure up on 6651; see module docs"]
async fn tls_handshake_fails_with_wrong_ca() {
    install_logger();
    let build = Pulsar::builder(TLS_URL, TokioExecutor)
        .with_certificate_chain_file(WRONG_CA)
        .expect("read wrong CA file")
        .with_tls_hostname_verification_enabled(true)
        .with_auth(Authentication {
            name: "token".into(),
            data: admin_token().into_bytes(),
        })
        .build();

    match tokio::time::timeout(HANDSHAKE_BUDGET, build).await {
        Ok(Ok(_pulsar)) => panic!(
            "connected successfully while trusting only an unrelated CA — TLS \
             verification is not actually happening"
        ),
        Ok(Err(e)) => {
            eprintln!("observed expected failure with the wrong CA: {e:?}");
        }
        Err(_) => panic!(
            "connect timed out after {HANDSHAKE_BUDGET:?} instead of failing fast \
             on certificate verification"
        ),
    }
}

/// Negative case #2: no trusted CA supplied at all (default OS trust store,
/// which does not include our self-signed CA). Must also fail, for the same
/// reason as the wrong-CA case.
#[tokio::test]
#[ignore = "requires broker-pulsar-secure up on 6651; see module docs"]
async fn tls_handshake_fails_with_no_ca_configured() {
    install_logger();
    let build = Pulsar::builder(TLS_URL, TokioExecutor)
        .with_tls_hostname_verification_enabled(true)
        .with_auth(Authentication {
            name: "token".into(),
            data: admin_token().into_bytes(),
        })
        .build();

    match tokio::time::timeout(HANDSHAKE_BUDGET, build).await {
        Ok(Ok(_pulsar)) => panic!(
            "connected successfully while trusting only the default OS CA store — \
             the broker's self-signed cert should never validate against that"
        ),
        Ok(Err(e)) => {
            eprintln!("observed expected failure with no configured CA: {e:?}");
        }
        Err(_) => panic!(
            "connect timed out after {HANDSHAKE_BUDGET:?} instead of failing fast \
             on certificate verification"
        ),
    }
}

/// Negative case #3: correct CA (so this is purely about auth, not TLS), but
/// a garbage token. Must surface as a recognizable authentication failure
/// within the handshake budget, not a hang — a hang here would be
/// indistinguishable from the broker never checking the token at all.
#[tokio::test]
#[ignore = "requires broker-pulsar-secure up on 6651; see module docs"]
async fn tls_handshake_fails_with_invalid_token() {
    install_logger();
    let build = Pulsar::builder(TLS_URL, TokioExecutor)
        .with_certificate_chain_file(CORRECT_CA)
        .expect("read correct CA file")
        .with_tls_hostname_verification_enabled(true)
        .with_auth(Authentication {
            name: "token".into(),
            data: b"this-is-not-a-valid-jwt".to_vec(),
        })
        .build();

    match tokio::time::timeout(HANDSHAKE_BUDGET, build).await {
        Ok(Ok(_pulsar)) => panic!(
            "connected successfully with a garbage token — authentication is not \
             actually being enforced over this TLS port"
        ),
        Ok(Err(e)) => {
            eprintln!("observed expected authentication failure: {e:?}");
        }
        Err(_) => panic!(
            "connect timed out after {HANDSHAKE_BUDGET:?} instead of returning a \
             recognizable authentication error"
        ),
    }
}
