import type { CoverageSummary, DocumentationRevision, EndpointDoc, EvidenceGap, RequestClassAnalysis, ResponseClassAnalysis } from "./types.js";
import type { EvidenceValidation } from "./evidence.js";
export function deriveCoverage(input: { endpointKey: string; schemaGaps: EvidenceGap[]; requestAnalysis: RequestClassAnalysis; responseAnalysis: ResponseClassAnalysis; revisionTrust: DocumentationRevision["trust"]; evidenceValidation: EvidenceValidation; testCoveredClassIds: string[]; runtimeObservedClassIds: string[]; runtimeEvidenceState: CoverageSummary["runtimeEvidenceState"] }): CoverageSummary {
  const blockers = [...input.schemaGaps, ...input.evidenceValidation.gaps, ...input.requestAnalysis.unresolvedConstraintIds.map((id) => ({ gapId: `gap_constraint_${id}`, code: "unresolved_constraint", message: `Constraint ${id} was not converted to a bounded partition.`, endpointKey: input.endpointKey, evidenceIds: [] })), ...input.responseAnalysis.unresolvedProducerIds.map((id) => ({ gapId: `gap_producer_${id}`, code: "unresolved_producer", message: `Response producer ${id} remains unresolved.`, endpointKey: input.endpointKey, producerId: id, evidenceIds: [] }))];
  if (input.revisionTrust === "fallback_live" || input.revisionTrust === "trust_unavailable") blockers.push({ gapId: `gap_trust_${input.endpointKey}`, code: "revision_trust_degraded", message: `Revision trust is ${input.revisionTrust}.`, endpointKey: input.endpointKey, evidenceIds: [] });
  if (input.runtimeEvidenceState === "unavailable" || input.runtimeEvidenceState === "partial") blockers.push({ gapId: `gap_runtime_${input.endpointKey}`, code: "runtime_evidence_unavailable", message: "Requested runtime evidence is unavailable or partial.", endpointKey: input.endpointKey, evidenceIds: [] });
  const dynamic = input.responseAnalysis.dynamicProducerIds.length;
  const level: CoverageSummary["level"] = blockers.length ? "partial" : dynamic ? "bounded" : "exhaustive";
  return { level, analyzedRequestPartitions: input.requestAnalysis.classes.length, unresolvedRequestConstraints: input.requestAnalysis.unresolvedConstraintIds.length, discoveredStaticExits: input.responseAnalysis.discoveredProducerIds.length, resolvedStaticExits: input.responseAnalysis.resolvedProducerIds.length, unresolvedDynamicProducers: input.responseAnalysis.unresolvedProducerIds.length, groupedDynamicProducers: dynamic, testCoveredClasses: input.testCoveredClassIds.length, runtimeObservedClasses: input.runtimeObservedClassIds.length, runtimeEvidenceState: input.runtimeEvidenceState, blockers: dedupeGaps(blockers) };
}
function dedupeGaps(gaps: EvidenceGap[]): EvidenceGap[] { return [...new Map(gaps.map((gap) => [`${gap.code}:${gap.endpointKey ?? ""}:${gap.fieldPath ?? ""}:${gap.producerId ?? ""}:${gap.revisionId ?? ""}`, gap])).values()]; }
export function aggregateDocumentCoverage(endpoints: EndpointDoc[]): CoverageSummary { const blockers = endpoints.flatMap((endpoint) => endpoint.coverage.blockers); const levels = endpoints.map((endpoint) => endpoint.coverage.level); const level = levels.includes("partial") ? "partial" : levels.includes("observed") ? "observed" : levels.includes("bounded") ? "bounded" : "exhaustive"; return { level, analyzedRequestPartitions: endpoints.reduce((n, endpoint) => n + endpoint.coverage.analyzedRequestPartitions, 0), unresolvedRequestConstraints: endpoints.reduce((n, endpoint) => n + endpoint.coverage.unresolvedRequestConstraints, 0), discoveredStaticExits: endpoints.reduce((n, endpoint) => n + endpoint.coverage.discoveredStaticExits, 0), resolvedStaticExits: endpoints.reduce((n, endpoint) => n + endpoint.coverage.resolvedStaticExits, 0), unresolvedDynamicProducers: endpoints.reduce((n, endpoint) => n + endpoint.coverage.unresolvedDynamicProducers, 0), groupedDynamicProducers: endpoints.reduce((n, endpoint) => n + endpoint.coverage.groupedDynamicProducers, 0), testCoveredClasses: endpoints.reduce((n, endpoint) => n + endpoint.coverage.testCoveredClasses, 0), runtimeObservedClasses: endpoints.reduce((n, endpoint) => n + endpoint.coverage.runtimeObservedClasses, 0), runtimeEvidenceState: endpoints.some((endpoint) => endpoint.coverage.runtimeEvidenceState === "partial") ? "partial" : endpoints.some((endpoint) => endpoint.coverage.runtimeEvidenceState === "available") ? "available" : "not_requested", blockers } };
export function coverageHeadings(summary: CoverageSummary): { request: "All Valid/Invalid Request Classes" | "Known Request Scenarios"; response: "All Possible Responses" | "Known Response Matrix" } { const all = summary.level === "exhaustive" || summary.level === "bounded"; return { request: all ? "All Valid/Invalid Request Classes" : "Known Request Scenarios", response: all ? "All Possible Responses" : "Known Response Matrix" }; }
