import { createHash } from "node:crypto";
import { createRevisionSetHash } from "./identity.js";
import { coverageHeadings } from "./coverage.js";
import type { ApiDocumentationIR, EndpointDoc, ManagedSection, RenderedDocument, ResponseClass, SchemaFieldDoc } from "./types.js";
function hash(value: string): string { return createHash("sha256").update(value).digest("hex").slice(0, 24); }
function esc(value: unknown): string { return String(value ?? "").replaceAll("|", "\\|").replaceAll("\n", " "); }
function fields(items: SchemaFieldDoc[], indent = ""): string[] { return items.flatMap((field) => [`${indent}- **${field.path || field.name}**: ${field.type} (${field.presence}${field.repeated ? ", repeated" : ""})${field.map ? ` map<${field.map.keyType}, ${field.map.valueType}>` : ""}${field.oneof ? ` oneof=${field.oneof}` : ""}${field.evidenceIds.length ? ` [${field.evidenceIds.join(", ")}]` : ""}`, ...(field.fields ? fields(field.fields, `${indent}  `) : [])]); }
function section(sectionKey: string, title: string, body: string): ManagedSection { const markdown = `## ${title}\n\n${body.trim()}\n`; const larkXml = `<h2>${title}</h2><p>${body.trim().replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;")}</p>`; return { sectionKey, title, markdown, larkXml, contentHash: hash(markdown) }; }
function endpointSection(endpoint: EndpointDoc): ManagedSection {
  const headings = coverageHeadings(endpoint.coverage);
  const requestRows = endpoint.requestClasses.map((item) => `| ${esc(item.scenario)} | ${item.validity} | ${esc(item.bodyPartitions.join(", "))} | ${item.evidenceIds.join(", ")} |`).join("\n") || "| _(none)_ | - | - | - |";
  const responseRows = endpoint.responseClasses.map((item) => `| ${esc(item.trigger)} | ${esc(item.transport.protocol)} ${esc(item.transport.status)} | ${item.bodyPresence} | ${esc(item.messageClass.pattern ?? item.messageClass.values?.join(", ") ?? "-")} | ${item.evidenceIds.join(", ")} |`).join("\n") || "| _(none)_ | - | - | - | - |";
  const body = [`**Route:** \`${endpoint.route}\`  `, `**Service / method:** \`${endpoint.service}.${endpoint.method}\`  `, `**Protocol:** ${endpoint.protocol}`, "", "### HEADER", endpoint.headers.length ? endpoint.headers.map((h) => `- **${h.name}**${h.required ? " (required)" : ""}: ${h.description} [${h.evidenceIds.join(", ")}]`).join("\n") : "_(none)_", "", "### REQUEST", fields(endpoint.requestSchema).join("\n") || "_(schema unavailable)_", "", "### RESPONSE", fields(endpoint.responseSchema).join("\n") || "_(schema unavailable)_", "", `### ${headings.request}`, "| Scenario | Validity | Partitions | Evidence |", "|---|---|---|---|", requestRows, "", `### ${headings.response}`, "| Trigger | Transport | Body | Message | Evidence |", "|---|---|---|---|---|", responseRows, "", "### Evidence Gaps", endpoint.gaps.length ? endpoint.gaps.map((gap) => `- **${gap.code}**: ${gap.message}`).join("\n") : "_(none)_", "", endpoint.examples.length ? `### Examples\n${endpoint.examples.map((example) => `- **${example.label}** (${example.origin}):\n\n  \`\`\`json\n  ${JSON.stringify(example.value)}\n  \`\`\``).join("\n")}` : ""].join("\n");
  return section(`endpoint:${endpoint.endpointKey}`, `${endpoint.service}.${endpoint.method}`, body);
}
export function renderApiDocumentation(ir: ApiDocumentationIR): RenderedDocument {
  const sections: ManagedSection[] = [];
  sections.push(section("summary", "Generation coverage and evidence freshness", [`- **Document:** ${ir.documentKey}`, `- **Coverage:** ${ir.coverage.level}`, `- **Request partitions:** ${ir.coverage.analyzedRequestPartitions}`, `- **Static exits:** ${ir.coverage.resolvedStaticExits}/${ir.coverage.discoveredStaticExits}`, `- **Runtime evidence:** ${ir.coverage.runtimeEvidenceState}`, `- **Revisions:** ${ir.revisions.map((revision) => `${revision.repo}@${revision.commitSha} (${revision.trust})`).join(", ") || "none"}`].join("\n")));
  if (ir.enums.length) sections.push(section("enums", "Enums", ir.enums.sort((a, b) => a.name.localeCompare(b.name)).map((item) => `### ${item.name}\n\n${item.values.length > 50 ? `${item.values.slice(0, 20).map((value) => `- ${value.name}`).join("\n")}\n- … ${item.values.length} values total (full values retained in IR)` : item.values.map((value) => `- ${value.name}${value.number == null ? "" : ` = ${value.number}`}`).join("\n")}`).join("\n\n")));
  sections.push(...ir.endpoints.map(endpointSection));
  if (ir.websocketEvents.length) sections.push(section("events", "WebSocket / Events", ir.websocketEvents.map((event) => `### ${event.name}\n- direction: ${event.direction}\n- ${event.behavior}\n- payload: ${fields(event.payloadSchema).join("; ") || "none"}`).join("\n\n")));
  if (ir.commonResponses.length) sections.push(section("common-responses", "Common Responses", ir.commonResponses.map((response) => `- ${response.trigger}: ${response.messageClass.pattern ?? response.messageClass.values?.join(", ") ?? "-"}`).join("\n")));
  if (ir.frontendChecklist.length) sections.push(section("frontend-checklist", "Frontend Checklist", ir.frontendChecklist.map((item) => `- [ ] ${item.text} [${item.evidenceIds.join(", ")}]`).join("\n")));
  sections.push(section("evidence-gaps-sources", "Evidence Gaps and Sources", ir.gaps.length ? ir.gaps.map((gap) => `- **${gap.code}**: ${gap.message}${gap.evidenceIds.length ? ` [${gap.evidenceIds.join(", ")}]` : ""}`).join("\n") : "_(none)_"));
  const revisionSetHash = createRevisionSetHash(ir.revisions);
  const managedSections = sections.map((item) => ({ ...item, larkXml: `<p style=\"color:#999999\">PENGUIN_API_DOC_BEGIN:v1:${ir.documentKey}:${item.sectionKey}</p>${item.larkXml}<p style=\"color:#999999\">PENGUIN_API_DOC_END:v1:${ir.documentKey}:${item.sectionKey}</p>` }));
  return { documentKey: ir.documentKey, revisionSetHash, coverage: ir.coverage, sections: managedSections, markdown: `# ${ir.title}\n\n${managedSections.map((item) => item.markdown).join("\n")}`, larkXml: managedSections.map((item) => item.larkXml).join("\n") };
}
