import { existsSync, mkdirSync, readFileSync, readdirSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { createHash, randomUUID } from "node:crypto";
import type { ApiDocPreview, ApiDocPreviewManifest, ApiDocPreviewPruneResult, ApiDocPreviewSaveResult, ApiDocPreviewDiff, ApiDocumentationIR, RenderedDocument } from "./types.js";
function safe(value: string): string { return createHash("sha256").update(value).digest("hex").slice(0, 32); }
function previewId(documentKey: string, revisionSetHash: string): string { return `preview:v1:${safe(documentKey)}:${safe(revisionSetHash)}`; }
function dirName(id: string): string { return id.replaceAll(":", "_"); }
function writeAtomic(path: string, value: string): void { const temp = `${path}.${process.pid}.${randomUUID()}.tmp`; writeFileSync(temp, value); renameSync(temp, path); }
export class ApiDocPreviewStore {
  constructor(private readonly rootDir: string) { mkdirSync(rootDir, { recursive: true }); }
  private location(id: string): string { return join(this.rootDir, dirName(id)); }
  private loadManifest(id: string): ApiDocPreviewManifest { return JSON.parse(readFileSync(join(this.location(id), "manifest.json"), "utf8")) as ApiDocPreviewManifest; }
  save(input: { ir: ApiDocumentationIR; rendered: RenderedDocument; mode: ApiDocPreviewManifest["mode"]; protectedBy?: ApiDocPreviewManifest["protectedBy"]; now?: Date }): ApiDocPreviewSaveResult {
    const id = previewId(input.ir.documentKey, input.rendered.revisionSetHash), dir = this.location(id), now = (input.now ?? new Date()).toISOString();
    const current = existsSync(join(dir, "manifest.json")) ? this.load(id) : null;
    if (current && current.rendered.markdown === input.rendered.markdown && JSON.stringify(current.ir) === JSON.stringify(input.ir)) return { status: "no_change", previewId: id, manifest: current.manifest };
    if (current && current.manifest.mode === "canonical" && current.rendered.revisionSetHash === input.rendered.revisionSetHash) return { status: "immutable_revision_conflict", previewId: id, reason: "canonical preview is immutable for this revision set" };
    const manifest: ApiDocPreviewManifest = { previewId: id, documentKey: input.ir.documentKey, revisionSetHash: input.rendered.revisionSetHash, mode: input.mode, title: input.ir.title, subjects: input.ir.endpoints.map((endpoint) => ({ service: endpoint.service, method: endpoint.method, route: endpoint.route })), searchTerms: [...new Set(input.ir.endpoints.flatMap((endpoint) => [endpoint.service, endpoint.method, endpoint.route]))], coverage: input.ir.coverage.level, sectionHashes: Object.fromEntries(input.rendered.sections.map((section) => [section.sectionKey, section.contentHash])), revisionIds: input.ir.revisions.map((revision) => revision.revisionId), sourceCommits: Object.fromEntries(input.ir.revisions.map((revision) => [revision.repo, revision.commitSha])), createdAt: current?.manifest.createdAt ?? now, updatedAt: now, protectedBy: [...new Set([...(current?.manifest.protectedBy ?? []), ...(input.protectedBy ?? [])])] };
    mkdirSync(dir, { recursive: true });
    writeAtomic(join(dir, "ir.json"), JSON.stringify(input.ir, null, 2)); writeAtomic(join(dir, "document.md"), input.rendered.markdown); writeAtomic(join(dir, "document.xml"), input.rendered.larkXml); writeAtomic(join(dir, "manifest.json"), JSON.stringify(manifest, null, 2));
    return { status: current ? "updated" : "created", previewId: id, manifest };
  }
  load(id: string): ApiDocPreview { return this.loadWithRendered(id); }
  private loadWithRendered(id: string): ApiDocPreview { const dir = this.location(id); const manifest = this.loadManifest(id); const ir = JSON.parse(readFileSync(join(dir, "ir.json"), "utf8")) as ApiDocumentationIR; const markdown = readFileSync(join(dir, "document.md"), "utf8"); const larkXml = readFileSync(join(dir, "document.xml"), "utf8"); return { manifest, ir, rendered: { documentKey: manifest.documentKey, revisionSetHash: manifest.revisionSetHash, coverage: ir.coverage, sections: Object.entries(manifest.sectionHashes).map(([sectionKey, contentHash]) => ({ sectionKey, title: sectionKey, markdown: "", larkXml: "", contentHash })), markdown, larkXml } }; }
  list(filter: { documentKey?: string; mode?: ApiDocPreviewManifest["mode"]; query?: string } = {}): ApiDocPreviewManifest[] { return readdirSync(this.rootDir, { withFileTypes: true }).filter((entry) => entry.isDirectory()).flatMap((entry) => { try { return [this.loadManifest(entry.name.replaceAll("_", ":"))]; } catch { return []; } }).filter((manifest) => (!filter.documentKey || manifest.documentKey === filter.documentKey) && (!filter.mode || manifest.mode === filter.mode) && (!filter.query || `${manifest.title} ${manifest.searchTerms.join(" ")}`.toLowerCase().includes(filter.query.toLowerCase()))); }
  diff(leftPreviewId: string, rightPreviewId: string): ApiDocPreviewDiff { const left = this.loadWithRendered(leftPreviewId), right = this.loadWithRendered(rightPreviewId); const keys = new Set([...Object.keys(left.manifest.sectionHashes), ...Object.keys(right.manifest.sectionHashes)]); const addedSectionKeys = [...keys].filter((key) => !left.manifest.sectionHashes[key] && !!right.manifest.sectionHashes[key]); const removedSectionKeys = [...keys].filter((key) => !!left.manifest.sectionHashes[key] && !right.manifest.sectionHashes[key]); const changedSectionKeys = [...keys].filter((key) => left.manifest.sectionHashes[key] && right.manifest.sectionHashes[key] && left.manifest.sectionHashes[key] !== right.manifest.sectionHashes[key]); return { status: addedSectionKeys.length || removedSectionKeys.length || changedSectionKeys.length ? "changed" : "no_documented_change", addedSectionKeys, removedSectionKeys, changedSectionKeys, markdownDiff: left.rendered.markdown === right.rendered.markdown ? "" : `--- ${leftPreviewId}\n+++ ${rightPreviewId}\n${right.rendered.markdown}` }; }
  setProtection(id: string, reason: ApiDocPreviewManifest["protectedBy"][number], enabled: boolean): ApiDocPreviewManifest { const manifest = this.loadManifest(id); const protectedBy = enabled ? [...new Set([...manifest.protectedBy, reason])] : manifest.protectedBy.filter((item) => item !== reason); writeAtomic(join(this.location(id), "manifest.json"), JSON.stringify({ ...manifest, protectedBy, updatedAt: new Date().toISOString() }, null, 2)); return this.loadManifest(id); }
  prune(input: { keepRevisionIds: string[]; hotLimit: number; coldBefore: Date }): ApiDocPreviewPruneResult { const manifests = this.list(); const protectedPreviewIds = manifests.filter((manifest) => manifest.protectedBy.length).map((manifest) => manifest.previewId); const sorted = manifests.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); const retained = sorted.slice(0, input.hotLimit).map((manifest) => manifest.previewId); const removedPreviewIds: string[] = []; for (const manifest of sorted.slice(input.hotLimit)) { const protectedItem = manifest.protectedBy.length || manifest.revisionIds.some((id) => input.keepRevisionIds.includes(id)); if (protectedItem || new Date(manifest.updatedAt) >= input.coldBefore) continue; rmSync(this.location(manifest.previewId), { recursive: true, force: true }); removedPreviewIds.push(manifest.previewId); } return { removedPreviewIds, retainedPreviewIds: this.list().map((manifest) => manifest.previewId), protectedPreviewIds }; }
}
