export interface DocumentationSubject { repo?: string; service?: string; method?: string; route?: string }
export interface DocumentationRequest {
  subjects: DocumentationSubject[];
  revision: { branch?: string; branches?: Record<string, string>; commitSha?: string; commits?: Record<string, string>; targetId?: string; deployedAt?: string };
  audience: "frontend" | "backend" | "operations";
  language: string;
  mode: "preview" | "draft" | "sync";
  includeRuntimeEvidence: boolean;
  runtimeScope?: { targetIds?: string[]; from: string; to: string; clues?: string[] };
}
export interface DocumentationRevision {
  revisionId: string; repoId: string; repo: string; branch?: string; commitSha: string; snapshotId?: string; mergeBaseSha?: string; worktreeFingerprint?: string;
  trust: "exact_commit" | "exact_worktree" | "fallback_live" | "trust_unavailable";
  resolutionSource: "commit" | "log_commit" | "deployment" | "indexed_commit" | "environment_branch" | "branch" | "worktree" | "live_fallback";
  degradationReason?: string;
}
export interface EvidenceRef { evidenceId: string; source: "schema" | "code" | "test" | "wiki" | "sls" | "synthetic"; revisionId?: string; locator: string; excerpt?: string; status: "verified" | "reviewed" | "observed" | "synthetic" | "inference"; freshness?: "fresh" | "stale" | "trust_unavailable"; targetId?: string; observedAt?: string }
export type CoverageLevel = "exhaustive" | "bounded" | "observed" | "partial";
export interface EvidenceGap { gapId: string; code: string; message: string; endpointKey?: string; fieldPath?: string; producerId?: string; revisionId?: string; evidenceIds: string[] }
export interface SchemaFieldDoc { path: string; name: string; type: string; presence: "required" | "optional" | "implicit"; repeated: boolean; description?: string; units?: string; format?: string; defaultValue?: string | number | boolean; enumRef?: string; map?: { keyType: string; valueType: string }; oneof?: string; fields?: SchemaFieldDoc[]; evidenceIds: string[] }
export interface EnumDoc { name: string; revisionId: string; values: Array<{ name: string; number?: number; description?: string }>; evidenceIds: string[] }
export interface ExampleDoc { exampleId: string; origin: "test" | "wiki" | "sls" | "synthetic"; synthetic: boolean; label: string; value: unknown; revisionId?: string; targetId?: string; observedAt?: string; evidenceIds: string[] }
export interface RequestClass { scenarioId: string; scenario: string; headers: string[]; bodyPartitions: string[]; preconditions: string[]; validity: "valid" | "invalid"; expectedOutcomeClassIds: string[]; sideEffectRisk: "none" | "read" | "write" | "unknown"; evidenceIds: string[]; coverage: CoverageLevel }
export interface ResponseClass { outcomeClassId: string; trigger: string; requestClassIds: string[]; preconditions: string[]; transport: { protocol: string; status?: string | number }; businessStatus?: string | number; bodyPresence: "present" | "absent" | "conditional"; bodyShape?: string; messageClass: { kind: "exact" | "static_set" | "dynamic_dependency"; values?: string[]; pattern?: string; producer?: string }; sideEffects: string[]; retry: "safe" | "unsafe" | "conditional" | "unknown"; frontendAction?: string; revisionId: string; evidenceIds: string[]; examples: ExampleDoc[]; coverage: CoverageLevel }
export interface CoverageSummary { level: CoverageLevel; analyzedRequestPartitions: number; unresolvedRequestConstraints: number; discoveredStaticExits: number; resolvedStaticExits: number; unresolvedDynamicProducers: number; groupedDynamicProducers: number; testCoveredClasses: number; runtimeObservedClasses: number; runtimeEvidenceState: "available" | "not_requested" | "unavailable" | "partial"; blockers: EvidenceGap[] }
export interface EndpointDoc { endpointKey: string; revisionId: string; service: string; method: string; route: string; protocol: string; description: string; dependencies: string[]; headers: Array<{ name: string; required: boolean; description: string; evidenceIds: string[] }>; requestSchema: SchemaFieldDoc[]; responseSchema: SchemaFieldDoc[]; requestClasses: RequestClass[]; responseClasses: ResponseClass[]; examples: ExampleDoc[]; frontendGuidance: string[]; evidenceIds: string[]; gaps: EvidenceGap[]; coverage: CoverageSummary }
export interface EventDoc { eventKey: string; revisionId: string; name: string; direction: "client_to_server" | "server_to_client" | "bidirectional"; payloadSchema: SchemaFieldDoc[]; behavior: string; evidenceIds: string[]; gaps: EvidenceGap[] }
export interface ChecklistItem { key: string; text: string; evidenceIds: string[] }
export interface ApiDocumentationIR { documentKey: string; title: string; revisions: DocumentationRevision[]; enums: EnumDoc[]; endpoints: EndpointDoc[]; websocketEvents: EventDoc[]; commonResponses: ResponseClass[]; frontendChecklist: ChecklistItem[]; evidence: EvidenceRef[]; gaps: EvidenceGap[]; coverage: CoverageSummary }
export interface DocumentationRequestValidation { ok: boolean; request?: DocumentationRequest; errors: Array<{ path: string; code: string; message: string }> }
export interface ResolvedSubject { subjectId: string; identityKey: string; repoId: string; repo: string; endpointKey: string; service: string; method: string; route: string; protocol: string }
export type SubjectResolution = { status: "resolved"; subjects: ResolvedSubject[] } | { status: "ambiguous_subject"; candidates: ResolvedSubject[]; reason: string } | { status: "not_found"; candidates: ResolvedSubject[]; reason: string };
export type RequestConstraintKind = "header" | "auth" | "routing" | "presence" | "type" | "enum" | "oneof" | "repeated" | "map" | "range" | "format" | "cross_field" | "state" | "idempotency";
export interface EndpointFact { endpointKey: string; revisionId: string; service: string; method: string; route: string; protocol: string; description?: string; requestFields: SchemaFieldDoc[]; responseFields: SchemaFieldDoc[]; enums: EnumDoc[]; schemaGaps: EvidenceGap[]; evidenceIds: string[] }
export interface RequestConstraintFact { constraintId: string; endpointKey: string; kind: RequestConstraintKind; fieldPath?: string; description: string; validPartitions: string[]; invalidPartitions: string[]; preconditions: string[]; expectedOutcomeClassIds: string[]; sideEffectRisk: "none" | "read" | "write" | "unknown"; evidenceIds: string[] }
export type ResponseProducerKind = "explicit_return" | "business_branch" | "validation_failure" | "transport_throw" | "catch" | "fallback" | "degraded_success" | "dependency_failure" | "state_outcome" | "test" | "runtime";
export interface ResponseProducerFact { producerId: string; endpointKey: string; kind: ResponseProducerKind; trigger: string; requestClassIds: string[]; preconditions: string[]; transport: { protocol: string; status?: string | number }; businessStatus?: string | number; bodyPresence: "present" | "absent" | "conditional"; bodyShape?: string; messageClass: ResponseClass["messageClass"]; sideEffects: string[]; retry: ResponseClass["retry"]; frontendAction?: string; revisionId: string; evidenceIds: string[] }
export interface CodeBehaviorFact { factId: string; kind: "guard" | "validator" | "return" | "throw" | "catch" | "fallback" | "dependency" | "side_effect" | "frontend_guidance"; statement: string; revisionId: string; constraintIds: string[]; producerIds: string[]; evidenceIds: string[] }
export interface TestFact { factId: string; revisionId: string; coveredConstraintIds: string[]; coveredProducerIds: string[]; examples: ExampleDoc[]; evidenceIds: string[] }
export interface WikiFact { factId: string; revisionId?: string; status: "reviewed" | "draft" | "stale"; statement: string; examples: ExampleDoc[]; evidenceIds: string[] }
export interface EventFact { eventKey: string; revisionId: string; name: string; direction: EventDoc["direction"]; payloadFields: SchemaFieldDoc[]; behavior?: string; evidenceIds: string[] }
export interface ChecklistFact { key: string; text: string; endpointKey?: string; revisionId?: string; evidenceIds: string[] }
export interface RuntimeEvidenceObservation { observationId: string; targetId: string; observedAt: string; endpointKey?: string; requestClassId?: string; responseClassId?: string; payload: unknown; evidenceIds: string[] }
export interface RuntimeEvidenceResult { status: "available" | "partial" | "unavailable"; observations: RuntimeEvidenceObservation[]; evidence: EvidenceRef[]; gaps: EvidenceGap[] }
export interface RuntimeEvidenceProvider { collect(input: { request: DocumentationRequest; subjects: ResolvedSubject[]; revisions: DocumentationRevision[] }): Promise<RuntimeEvidenceResult> }
export interface DocumentationFactBundle { request: DocumentationRequest; subjects: ResolvedSubject[]; revisions: DocumentationRevision[]; endpoints: EndpointFact[]; requestConstraints: RequestConstraintFact[]; responseProducers: ResponseProducerFact[]; codeFacts: CodeBehaviorFact[]; testFacts: TestFact[]; wikiFacts: WikiFact[]; eventFacts: EventFact[]; checklistFacts: ChecklistFact[]; runtime: RuntimeEvidenceResult; evidence: EvidenceRef[]; gaps: EvidenceGap[] }
export type DocumentationCollectionResult = { status: "collected"; bundle: DocumentationFactBundle } | { status: "ambiguous_subject"; candidates: ResolvedSubject[]; reason: string } | { status: "ambiguous_revision"; repos: string[]; reason: string } | { status: "not_found"; candidates: ResolvedSubject[]; reason: string };
export interface DocumentationSourceAdapter { resolveSubjects(subjects: DocumentationSubject[]): Promise<SubjectResolution>; resolveRevisions(request: DocumentationRequest, subjects: ResolvedSubject[]): Promise<DocumentationRevision[]>; collectEndpoint(subject: ResolvedSubject, revision: DocumentationRevision): Promise<EndpointFact>; collectRequestConstraints(subject: ResolvedSubject, revision: DocumentationRevision): Promise<RequestConstraintFact[]>; collectResponseProducers(subject: ResolvedSubject, revision: DocumentationRevision): Promise<ResponseProducerFact[]>; collectCodeFacts(subject: ResolvedSubject, revision: DocumentationRevision): Promise<CodeBehaviorFact[]>; collectTestFacts(subject: ResolvedSubject, revision: DocumentationRevision): Promise<TestFact[]>; collectWikiFacts(subject: ResolvedSubject, revision: DocumentationRevision): Promise<WikiFact[]>; collectEvents(subject: ResolvedSubject, revision: DocumentationRevision): Promise<EventFact[]>; collectChecklistFacts(subject: ResolvedSubject, revision: DocumentationRevision): Promise<ChecklistFact[]>; collectRuntimeEvidence?(request: DocumentationRequest, subjects: ResolvedSubject[], revisions: DocumentationRevision[]): Promise<RuntimeEvidenceResult> }
export interface RequestClassAnalysis { classes: RequestClass[]; analyzedConstraintIds: string[]; unresolvedConstraintIds: string[]; generationStrategy: "equivalence_boundary_pairwise" }
export interface ResponseClassAnalysis { classes: ResponseClass[]; discoveredProducerIds: string[]; resolvedProducerIds: string[]; unresolvedProducerIds: string[]; dynamicProducerIds: string[] }
export interface ManagedSection { sectionKey: string; title: string; markdown: string; larkXml: string; contentHash: string }
export interface RenderedDocument { documentKey: string; revisionSetHash: string; coverage: CoverageSummary; sections: ManagedSection[]; markdown: string; larkXml: string }
export interface ManagedBlockInput { blockId: string; topLevelIndex: number; xml: string }
export interface ParsedManagedSection { sectionKey: string; beginBlockId: string; contentBlockIds: string[]; endBlockId: string; contentHash: string; canonicalXml: string }
export interface ManagedSectionParseResult { status: "ok" | "structural_conflict"; sections: ParsedManagedSection[]; unmanagedBlockIds: string[]; errors: Array<{ code: string; sectionKey?: string; blockIds: string[] }> }
export interface ApiDocPreviewManifest { previewId: string; documentKey: string; revisionSetHash: string; mode: "preview" | "draft" | "canonical" | "conflict"; title: string; subjects: DocumentationSubject[]; searchTerms: string[]; coverage: CoverageLevel; sectionHashes: Record<string, string>; revisionIds: string[]; sourceCommits: Record<string, string>; createdAt: string; updatedAt: string; protectedBy: Array<"default" | "deployment" | "pin" | "lark_draft" | "conflict"> }
export interface ApiDocPreview { manifest: ApiDocPreviewManifest; ir: ApiDocumentationIR; rendered: RenderedDocument; conflict?: ApiDocConflictPreview }
export interface ApiDocConflictPreview { baseRevisionId: number; currentRevisionId: number; sectionKeys: string[]; baseHashes: Record<string, string>; currentHashes: Record<string, string>; desiredHashes: Record<string, string>; markdownDiff: string }
export type ApiDocPreviewSaveResult = { status: "created" | "updated" | "no_change"; previewId: string; manifest: ApiDocPreviewManifest } | { status: "immutable_revision_conflict"; previewId: string; reason: string };
export interface ApiDocPreviewDiff { status: "changed" | "no_documented_change"; addedSectionKeys: string[]; removedSectionKeys: string[]; changedSectionKeys: string[]; markdownDiff: string }
export interface ApiDocPreviewPruneResult { removedPreviewIds: string[]; retainedPreviewIds: string[]; protectedPreviewIds: string[] }
