import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { createHash } from "node:crypto";
export interface GitRefEntry { fullName: string; shortName: string; kind: "local" | "remote" | "tag"; commitSha: string }
export interface GitRefCatalogue { refs: GitRefEntry[]; remoteHead?: string; shallow: boolean }
export type DefaultBranchResolution = { status: "resolved"; name: string; source: "config" | "remote_head" | "local_main" | "local_master" } | { status: "explicit_base_required"; candidates: string[]; reason: string };
export interface ResolvedRevisionTopology { repoRoot: string; branch?: string; headSha: string; treeHash: string; parentShas: string[]; defaultBranch?: string; baseBranch?: string; mergeBaseSha?: string; ahead: number | null; behind: number | null; historyState: "complete" | "shallow" | "missing_history"; sourceKind: "git_tree" | "worktree"; worktreeFingerprint?: string; dirtyFiles: string[] }
export interface ResolveRevisionTopologyOptions { configuredDefault?: string; explicitBase?: string; indexedAncestors?: string[]; includeDirtyWorktree?: boolean }
export interface GitTreeFile { path: string; blobSha: string; mode: string }
function git(root: string, args: string[]): string { return execFileSync("git", ["-C", root, ...args], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim(); }
export class GitObjectReader { constructor(private readonly repoRoot: string) {} listTree(commitSha: string): GitTreeFile[] { const raw = execFileSync("git", ["-C", this.repoRoot, "ls-tree", "-r", "-z", commitSha], { encoding: "buffer" }).toString(); return raw.split("\0").filter(Boolean).map((entry) => { const [meta, path] = entry.split("\t"); const [mode, , blobSha] = meta.split(" "); return { path, blobSha, mode }; }); } readBlob(blobSha: string): Buffer { return execFileSync("git", ["-C", this.repoRoot, "cat-file", "blob", blobSha]); } readTextAtCommit(commitSha: string, filePath: string): string | null { try { return this.readBlob(git(this.repoRoot, ["rev-parse", `${commitSha}:${filePath}`])).toString("utf8"); } catch { return null; } } }
export function catalogGitRefs(repoRoot: string): GitRefCatalogue { const refs: GitRefEntry[] = []; try { const raw = git(repoRoot, ["for-each-ref", "--format=%(refname)\t%(objectname)", "refs/heads", "refs/remotes", "refs/tags"]); for (const line of raw.split("\n").filter(Boolean)) { const [fullName, commitSha] = line.split("\t"); const kind = fullName.startsWith("refs/tags/") ? "tag" : fullName.startsWith("refs/remotes/") ? "remote" : "local"; refs.push({ fullName, commitSha, kind, shortName: fullName.replace(/^refs\/(heads|remotes|tags)\//, "") }); } } catch { return { refs: [], shallow: false }; } let remoteHead: string | undefined; try { remoteHead = git(repoRoot, ["symbolic-ref", "--short", "refs/remotes/origin/HEAD"]).replace(/^origin\//, ""); } catch { /* no remote head */ } const gitDir = git(repoRoot, ["rev-parse", "--git-dir"]); const shallow = existsSync(gitDir + "/shallow") && readFileSync(gitDir + "/shallow", "utf8").trim().length > 0; return { refs, ...(remoteHead ? { remoteHead } : {}), shallow }; }
export function resolveDefaultBranch(repoRoot: string, options: { configured?: string }): DefaultBranchResolution { const catalogue = catalogGitRefs(repoRoot); if (options.configured && catalogue.refs.some((ref) => ref.kind === "local" && ref.shortName === options.configured)) return { status: "resolved", name: options.configured, source: "config" }; if (catalogue.remoteHead && catalogue.refs.some((ref) => ref.kind === "local" && ref.shortName === catalogue.remoteHead)) return { status: "resolved", name: catalogue.remoteHead, source: "remote_head" }; const locals = catalogue.refs.filter((ref) => ref.kind === "local").map((ref) => ref.shortName); if (locals.includes("main")) return { status: "resolved", name: "main", source: "local_main" }; if (locals.includes("master")) return { status: "resolved", name: "master", source: "local_master" }; return { status: "explicit_base_required", candidates: locals.sort(), reason: "no verified default branch" }; }
export function resolveRevisionTopology(repoRoot: string, revision: { branch?: string; commitSha?: string; useWorktree?: boolean }, options: ResolveRevisionTopologyOptions = {}): ResolvedRevisionTopology { const branch = revision.branch; const headSha = git(repoRoot, ["rev-parse", revision.commitSha ?? (branch ? `${branch}^{commit}` : "HEAD")]); const treeHash = git(repoRoot, ["rev-parse", `${headSha}^{tree}`]); const parentShas = git(repoRoot, ["rev-list", "--parents", "-n", "1", headSha]).split(" ").slice(1); const defaultResolution = resolveDefaultBranch(repoRoot, { configured: options.configuredDefault }); const defaultBranch = defaultResolution.status === "resolved" ? defaultResolution.name : undefined; const base = options.explicitBase ?? defaultBranch; let mergeBaseSha: string | undefined; let ahead: number | null = null, behind: number | null = null; let historyState: ResolvedRevisionTopology["historyState"] = catalogGitRefs(repoRoot).shallow ? "shallow" : "complete"; if (base) { try { mergeBaseSha = git(repoRoot, ["merge-base", headSha, `${base}^{commit}`]); const counts = git(repoRoot, ["rev-list", "--left-right", "--count", `${base}...${headSha}`]).split(/\s+/).map(Number); behind = counts[0] ?? null; ahead = counts[1] ?? null; } catch { historyState = "missing_history"; } } else historyState = "missing_history"; let dirtyFiles: string[] = []; let worktreeFingerprint: string | undefined; if (revision.useWorktree || !revision.commitSha && !branch) { try { dirtyFiles = git(repoRoot, ["status", "--porcelain=v1", "--untracked-files=all"]).split("\n").filter(Boolean).map((line) => line.slice(3)); } catch { historyState = "missing_history"; } worktreeFingerprint = createHash("sha256").update(`${headSha}\n${dirtyFiles.join("\n")}\n${dirtyFiles.map((file) => { try { return readFileSync(`${repoRoot}/${file}`); } catch { return ""; } }).join("\0")}`).digest("hex"); }
  return { repoRoot, ...(branch ? { branch } : {}), headSha, treeHash, parentShas, ...(defaultBranch ? { defaultBranch } : {}), ...(base && defaultBranch !== base ? { baseBranch: base } : {}), ...(mergeBaseSha ? { mergeBaseSha } : {}), ahead, behind, historyState, sourceKind: revision.useWorktree ? "worktree" : "git_tree", ...(worktreeFingerprint ? { worktreeFingerprint } : {}), dirtyFiles };
}
