import { readFileSync } from "node:fs";
import { basename, dirname, relative } from "node:path";

export interface ProtoEndpoint {
  /** e.g. "PlayerService" */
  service: string;
  /** e.g. "CheckPassword" (camelCase as written in proto) */
  method: string;
  /** The proto file path relative to repo root */
  filePath: string;
  /** Module name inferred from directory structure */
  module: string;
}

/**
 * Extract gRPC service + rpc method definitions from a .proto file.
 * Handles proto3 syntax, multi-line `rpc` declarations, and `//`/`* *`/ comments.
 */
export function parseProtoEndpoints(source: string, relPath: string): ProtoEndpoint[] {
  // Infer module from directory structure. For fly-style repos:
  //   apps/auth/player.proto → "auth"
  //   common/health-check.proto → "common"
  const dir = dirname(relPath);
  const parts = dir.split("/");
  // Skip "apps" prefix if present: apps/auth/foo.proto → auth
  const module = parts[0] === "apps" ? (parts[1] ?? parts[0]) : parts[0];

  // Strip comments (both // and /* */) to avoid matching service/rpc inside comments.
  const noComments = source
    .replace(/\/\*[\s\S]*?\*\//g, "") // block comments
    .replace(/\/\/.*$/gm, "");        // line comments

  const endpoints: ProtoEndpoint[] = [];

  // Locate each service header, then scan balanced braces. RPC declarations may
  // have their own `{ ... }` option blocks, so a regex body capture stops after
  // the first method and silently drops the rest of the service.
  const serviceRe = /\bservice\s+(\w+)\s*\{/g;
  let svcMatch;
  while ((svcMatch = serviceRe.exec(noComments)) !== null) {
    const serviceName = svcMatch[1];
    const openBrace = svcMatch.index + svcMatch[0].length - 1;
    let depth = 1;
    let cursor = openBrace + 1;
    while (depth > 0 && cursor < noComments.length) {
      if (noComments[cursor] === "{") depth += 1;
      else if (noComments[cursor] === "}") depth -= 1;
      cursor += 1;
    }
    const body = noComments.slice(openBrace + 1, depth === 0 ? cursor - 1 : noComments.length);
    serviceRe.lastIndex = cursor;

    // Match `rpc MethodName(RequestType) returns (ResponseType);` or multiline variants
    const rpcRe = /rpc\s+(\w+)\s*\(/g;
    let rpcMatch;
    while ((rpcMatch = rpcRe.exec(body)) !== null) {
      endpoints.push({
        service: serviceName,
        method: rpcMatch[1],
        filePath: relPath,
        module,
      });
    }
  }

  return endpoints;
}

/**
 * Parse all .proto files in a repo and return the discovered endpoints.
 * Walks `protoFiles` (generated by walkRepoFiles or similar), reads and parses each.
 */
export function collectProtoEndpoints(
  protoFiles: { absPath: string; relPath: string }[],
): ProtoEndpoint[] {
  const all: ProtoEndpoint[] = [];
  for (const f of protoFiles) {
    let source: string;
    try {
      source = readFileSync(f.absPath, "utf8");
    } catch {
      continue;
    }
    all.push(...parseProtoEndpoints(source, f.relPath));
  }
  return all;
}
