export const KNOWLEDGE_CORE_VERSION = "0.0.1";
export { canonicalJson, sha256Hex } from "./canonical.js";
export {
  Ledger,
  eventChecksum,
  readLedgerFile,
  type LedgerEvent,
  type LedgerEventInput,
  type LedgerMethod,
  type LedgerOrigin,
  type LedgerReadResult,
  type LedgerTarget,
} from "./ledger.js";
export { SCHEMA_VERSION, openDatabase } from "./schema.js";
export { materialize, LedgerGapError } from "./materializer.js";
export {
  KnowledgeStore,
  type NodeRow,
  type ParsedEdge,
  type SearchHit,
} from "./store.js";
export {
  search,
  getNodeDetail,
  exploreGraph,
  compareBranches,
  indexStatus,
  listSuggestions,
  listTags,
  listIndexedFiles,
  listFileSymbols,
  graphNeighborhood,
  repoGraph,
  buildContextPack,
  renderContextPackMarkdown,
  buildFlow,
  renderFlowMarkdown,
  affectedByFiles,
  architecture,
  deadCode,
  type AffectedResult,
  type ArchitectureOverview,
  type DeadCodeResult,
  branchFreshness,
  liveBranchOf,
  type BranchFreshness,
  type FlowResult,
  type FlowStep,
  type ContextPack,
  type ContextBrief,
  type GraphMode,
  type GraphResult,
  type NodeDetail,
  type BranchDiff,
  type IndexStatus,
  type SearchResultRow,
  type IndexedFileRow,
  type FileSymbolRow,
  type GraphView,
} from "./query.js";
