import { createHash, randomUUID } from "node:crypto";
import type { KnowledgeStore } from "./store.js";
export type MemoryClass = "session" | "project" | "decision" | "runbook" | "incident" | "preference";
export interface MemoryItem { id: string; class: MemoryClass; scope: { workspaceId?: string; repoId?: string; subject?: string }; subject: string; body: string; source: unknown[]; confidence: number; retention: "ephemeral" | "normal" | "indefinite"; status: "active" | "forgotten" | "stale"; expiresAt?: string; createdAt: string; updatedAt: string; }
export class MemoryStore {
  constructor(private readonly store: KnowledgeStore) {}
  remember(input: Omit<MemoryItem, "id" | "createdAt" | "updatedAt" | "status">): MemoryItem { const now = new Date(); const sessionExpiry = input.class === "session" && !input.expiresAt ? new Date(now.getTime() + 24 * 60 * 60 * 1000).toISOString() : input.expiresAt; const item: MemoryItem = { ...input, ...(sessionExpiry ? { expiresAt: sessionExpiry } : {}), id: `memory_${randomUUID()}`, status: "active", createdAt: now.toISOString(), updatedAt: now.toISOString() }; this.store.db.prepare("INSERT INTO memory_items(id,class,scope_json,subject,body,source_json,confidence,retention,status,expires_at,content_hash,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)").run(item.id,item.class,JSON.stringify(item.scope),item.subject,item.body,JSON.stringify(item.source),item.confidence,item.retention,item.status,item.expiresAt ?? null,createHash("sha256").update(item.body).digest("hex"),item.createdAt,item.updatedAt); return item; }
  recall(scope?: { workspaceId?: string; repoId?: string }): MemoryItem[] { const rows = this.store.db.prepare("SELECT * FROM memory_items WHERE status='active' AND (expires_at IS NULL OR expires_at>?) ORDER BY confidence DESC,updated_at DESC").all(new Date().toISOString()) as Array<Record<string, string | number>>; return rows.filter((row) => { const value = JSON.parse(String(row.scope_json)) as MemoryItem["scope"]; const workspaceOk = !scope?.workspaceId || !value.workspaceId || value.workspaceId === scope.workspaceId; const repoOk = !scope?.repoId || value.repoId === scope.repoId; return workspaceOk && repoOk; }).map((row) => ({ id: String(row.id), class: row.class as MemoryClass, scope: JSON.parse(String(row.scope_json)), subject: String(row.subject), body: String(row.body), source: JSON.parse(String(row.source_json)), confidence: Number(row.confidence), retention: row.retention as MemoryItem["retention"], status: row.status as MemoryItem["status"], ...(row.expires_at ? { expiresAt: String(row.expires_at) } : {}), createdAt: String(row.created_at), updatedAt: String(row.updated_at) })); }
  forget(id: string): void { this.store.db.prepare("UPDATE memory_items SET status='forgotten',body='',updated_at=? WHERE id=?").run(new Date().toISOString(), id); }
  markStaleByRevision(revisionId: string): number { const rows = this.store.db.prepare("SELECT id,source_json FROM memory_items WHERE status='active'").all() as Array<{ id: string; source_json: string }>; let changed = 0; for (const row of rows) { let source: unknown; try { source = JSON.parse(row.source_json); } catch { continue; } if (JSON.stringify(source).includes(revisionId)) changed += this.store.db.prepare("UPDATE memory_items SET status='stale',updated_at=? WHERE id=? AND status='active'").run(new Date().toISOString(), row.id).changes; } return changed; }
  promote(id: string, retention: "normal" | "indefinite" = "normal"): MemoryItem {
    const changed = this.store.db.prepare("UPDATE memory_items SET class=CASE WHEN class='session' THEN 'project' ELSE class END, retention=?, expires_at=NULL, updated_at=? WHERE id=? AND status='active'").run(retention, new Date().toISOString(), id);
    if (changed.changes === 0) throw new Error("MEMORY_NOT_FOUND");
    const row = this.recall().find((item) => item.id === id);
    if (!row) throw new Error("MEMORY_NOT_FOUND");
    return row;
  }
}
